name: description
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 10 * * 1'

jobs:
  update-docker-readme:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: jonakoudijs/theforest
